backend:
  name: github
  repo: meinrehlein/simone
  branch: main
  site_domain: simones.netlify.app
  site_id: e00f35ab-4e03-407c-85cd-3cbbf666a4fc
  base_url: https://simones.netlify.app 
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/data/projects"
    create: true
    extension: md
    slug: "{{slug}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Year, name: year, widget: number }
      - { label: Location, name: location, widget: string }
      - { label: Type, name: type, widget: string }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: src, widget: image }
          - { label: Alt Text, name: alt, widget: string }
      - { label: Body, name: body, widget: markdown }